New enclave UI
idos-network/idos-sdk-js pull request #214
Opened 2024-05-21 13:02 UTC by Strnadj

2024-05-21 14:01 UTC, juliosantos requested changes

2024-05-21 14:01 UTC, juliosantos commented on .gitignore
> +vite.config.ts.timestamp-*
What's this about?

2024-05-21 14:01 UTC, juliosantos commented on apps/idos-enclave/src/dialog.tsx
> +render(<App store={store} enclave={enclave} />, document.getElementById("app")!);
What does this `!` at the end do?

2024-05-21 14:01 UTC, juliosantos commented on apps/idos-enclave/src/pages/Header.tsx
> +        />
Please remove this — since the enclave experience is so brief, I'd rather not add another option for the user to wonder about

2024-05-21 14:01 UTC, juliosantos commented on apps/idos-enclave/src/pages/Header.tsx
> +        idOS Secure Enclave
```suggestion
        Secure Enclave
```

2024-05-21 14:01 UTC, juliosantos commented on apps/idos-enclave/src/pages/methods/Passkey.tsx
> +            <Collapsible title="What is a passkey?" Icon={QuestionMarkCircleIcon}>
Please make this smaller — it almost looks more important than the button :)

2024-05-21 14:04 UTC, Strnadj commented on .gitignore
> +vite.config.ts.timestamp-*
@ditoglez do you know why this file has been created? ...

2024-05-21 14:05 UTC, Strnadj commented on apps/idos-enclave/src/dialog.tsx
> +render(<App store={store} enclave={enclave} />, document.getElementById("app")!);
`document.getElementById` can return `null | HTML element` the `!` means that we are sure, that it returns a HTML element, not null

2024-05-21 15:59 UTC, ditoglez commented on .gitignore
> +vite.config.ts.timestamp-*
I guess this is why:
https://github.com/vitejs/vite/issues/13267

2024-05-21 16:05 UTC, ditoglez commented on apps/idos-enclave/src/dialog.tsx
> +render(<App store={store} enclave={enclave} />, document.getElementById("app")!);
Did `biome` not complain about it?. I am more then sure that it should.

2024-05-21 16:08 UTC, ditoglez commented on apps/idos-enclave/src/pages/App.tsx
> +    respondToEnclave({ error: "closed " });
Extra space over here.

2024-05-24 09:25 UTC, juliosantos requested changes

2024-05-24 09:25 UTC, juliosantos commented on apps/idos-example-dapp/src/main.js
> +      mode: "new",
whoops

2024-05-24 09:25 UTC, juliosantos commented on packages/idos-sdk-js/.env
> +VITE_IDOS_ENCLAVE_URL=https://localhost:5174/
whoops

2024-05-27 10:17 UTC, juliosantos approved these changes

2024-05-28 08:09 UTC, merged